export const projects = [
  {
    slug: "stylefinden",
    name: "Stylefinden",
    status: "Live",
    summary: "A place to discover personal style.",
    description: "A fashion discovery and editorial platform that brings together outfits, hairstyles, body-shape guides, and style inspiration.",
    role: "Co-Founder & Lead Developer",
    image: "/work/stylefinden-home.png",
    imageAlt: "Stylefinden homepage with outfit photography and fashion discovery navigation",
    imageWidth: 1200,
    imageHeight: 800,
    url: "https://stylefinden.com",
    stack: ["Next.js", "TypeScript", "Sanity", "Supabase", "Resend", "Vercel"],
    sections: [
      { title: "My work", text: "I built the platform from scratch and own the product engineering end to end: the application, CMS architecture, data systems, transactional email, analytics, and deployment." },
      { title: "Behind the scenes", text: "Stylefinden is also the production environment for my agentic engineering system. Project memory, specialist agents, reusable skills, and verification support development and content operations. I retain responsibility for architecture and production decisions." },
    ],
  },
  {
    slug: "wakesay",
    name: "WakeSay",
    status: "In development",
    summary: "A shared morning, even when you are apart.",
    description: "An iPhone app in development for couples to share morning and bedtime routines, exchange real voice recordings, and build habits together.",
    role: "Product design & engineering",
    image: "/work/wakesay-icon.png",
    imageAlt: "WakeSay app icon",
    imageWidth: 1024,
    imageHeight: 1024,
    url: null,
    stack: ["SwiftUI", "AlarmKit", "AVFoundation", "Supabase", "StoreKit"],
    sections: [
      { title: "What I’m building", text: "A shared routine for two: preparing an alarm for a partner, waking up to their recorded voice, and leaving a message for the morning. The new product direction also explores shared goals, achievements, and playful morning challenges, with a full interface redesign in progress." },
      { title: "My work", text: "I own product design and native iOS engineering, from pairing and sharing permissions to audio recording, alarm scheduling, and subscriptions. WakeSay is moving from an AI-voice alarm concept toward human connection; the new direction is in development, not a released feature set." },
    ],
  },
  {
    slug: "visual-plate",
    name: "Visual Plate",
    status: "In development",
    summary: "Understand the menu before you order.",
    description: "An AI-assisted iPhone app for travelers to scan unfamiliar menus, recognize dishes, and understand what they are about to order.",
    role: "Product design & engineering",
    image: "/work/visualplate.png",
    imageAlt: "Visual Plate app icon with a fork and knife on a dark background",
    imageWidth: 1024,
    imageHeight: 1024,
    url: null,
    stack: ["SwiftUI", "AVFoundation", "Vision", "Supabase", "AI matching", "MapKit"],
    sections: [
      { title: "What I’m building", text: "A camera-led experience that connects menu scanning and text recognition with dish matching, food imagery, and useful explanations. The wider product includes discovery, an AI assistant, and a personal library." },
    ],
  },
  {
    slug: "museum-of-my-mind",
    name: "Museum of My Mind",
    status: "Live",
    summary: "Photographs, memories, and visual fragments.",
    description: "A personal image archive for photographs and visual fragments, designed around gallery layouts and optimized image delivery.",
    role: "Design & development",
    image: "/work/museum.png",
    imageAlt: "Museum of My Mind personal photography archive",
    imageWidth: 1200,
    imageHeight: 800,
    url: "https://museumofmymind.com",
    stack: ["Photography", "Web design", "Image delivery"],
    sections: [
      { title: "My work", text: "I designed and developed the archive, with a focus on presenting imagery and delivering it efficiently across screen sizes." },
    ],
  },
] as const;

export const engineeringNotes: Record<string, { title: string; text: string }[]> = {
  stylefinden: [
    { title: "Treat AI output as application data", text: "LLM workflows use structured outputs and Zod validation, with request rate limiting and human review. The application checks what a model returns before relying on it." },
    { title: "Build for multiple markets", text: "Localization includes canonical and hreflang architecture alongside content and product feeds. Vitest and Playwright checks cover UI, APIs, localization, and SEO behavior." },
  ],
  wakesay: [
    { title: "Keep the alarm dependable", text: "AlarmKit is the scheduling core. Alarm reliability is kept independent from subscriptions, engagement features, and backend availability." },
    { title: "Make sharing intentional", text: "Partner interactions are built around explicit permissions and recipient control. A remote request is not treated as proof that an alarm has been scheduled or has rung; audio delivery and alarm behavior require physical-device verification." },
  ],
  "visual-plate": [
    { title: "A translation is only part of the answer", text: "The prototype combines menu text recognition with image recognition and location-aware analysis to help identify the actual dish." },
    { title: "Keep uncertainty visible", text: "Dish identity, imagery, and information confidence are treated separately. Caching and user feedback support the analysis without treating every AI result as certain." },
  ],
  "museum-of-my-mind": [
    { title: "Let the photographs lead", text: "A full-screen gallery keeps attention on the archive. Cloudinary delivery and connection-aware incremental loading support exploring imagery across devices." },
  ],
};
